import type { KnockoutMatch } from '../types'
import bracketRaw from './model/bracket.json'

export function makeSlug(a: string, b: string): string {
  return `${a.toLowerCase().replace(/ /g, '-')}-vs-${b.toLowerCase().replace(/ /g, '-')}`
}

// Official FIFA World Cup 2026 draw (December 5, 2024, Washington D.C.)
export const GROUPS: Record<string, string[]> = {
  A: ['Mexico',      'South Korea',  'South Africa',       'Czechia'],
  B: ['Canada',      'Switzerland',  'Qatar',              'Bosnia-Herz'],
  C: ['Brazil',      'Morocco',      'Scotland',           'Haiti'],
  D: ['USA',         'Paraguay',     'Australia',          'Turkey'],
  E: ['Germany',     'Curacao',      'Ivory Coast',        'Ecuador'],
  F: ['Netherlands', 'Japan',        'Sweden',             'Tunisia'],
  G: ['Belgium',     'Egypt',        'Iran',               'New Zealand'],
  H: ['Spain',       'Cape Verde',   'Saudi Arabia',       'Uruguay'],
  I: ['France',      'Senegal',      'Iraq',               'Norway'],
  J: ['Argentina',   'Algeria',      'Austria',            'Jordan'],
  K: ['Portugal',    'Congo DR',     'Uzbekistan',         'Colombia'],
  L: ['England',     'Croatia',      'Ghana',              'Panama'],
}

// The knockout bracket is generated by scripts/fit-model.js from the model
// applied to the real group draw above (seeded by model score, advanced by the
// higher win probability). It is rewritten on every refit, so it always stays
// consistent with GROUPS and the current weights. See lib/model/bracket.json.
export const ROUNDS: Record<string, KnockoutMatch[]> = (
  bracketRaw as { rounds: Record<string, KnockoutMatch[]> }
).rounds

export const BRACKET_GENERATED_AT: string = (bracketRaw as { generatedAt: string }).generatedAt

export const ROUND_LABELS: Record<string, string> = {
  r32: 'Round of 32',
  r16: 'Round of 16',
  qf: 'Quarter-Finals',
  sf: 'Semi-Finals',
  final: 'The Final',
}
